### PR TITLE
fix(tekton-PLR): add repo prefix to name

### PR DESCRIPTION
**Pull request by MartinBasti**
This allows us to easily identify in tekton namespace which PLRs belongs to clair-in-ci-db

### CODE REVIEW

**Review by hongweiliu17 — APPROVED** [review]
LGTM

**Comment by MartinBasti** [comment]
I had to update timeout in both build task and pipelinerun to pass CI.
Also update requests for CPU to schedule it better on OCP (didn't helped much though)

**Review by dirgim — APPROVED** [review]
LGTM

**Review by kasemAlem — APPROVED** [review]

**Review by sonam1412 — APPROVED** [review]
lgtm

**Pull request merged**
